name: deployment CI / CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Deploy
        run: echo deploying the app to AWS EC2

      - name: Stop existing process on port 3000
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
            PORT=3000
            PID=$(sudo lsof -t -i:$PORT)

            if [ -n "$PID" ]; then
              echo "Process found on port $PORT with PID: $PID"
              echo "Killing process...."
              sudo kill -9 $PID
              echo "Process killed successfully"
            else
              echo "No process found on port $PORT"
            fi'

      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
            cd /home/ubuntu/Goopim_Front &&
            sudo git pull &&
            sudo npm run build &&
            sudo npm start &"
